from __future__ import annotations

from typing import Any, Protocol


class ATSAdapter(Protocol):
    def search_candidate(self, email: str | None = None, phone: str | None = None, linkedin_url: str | None = None, name: str | None = None) -> list[dict[str, Any]]: ...
    def get_candidate_history(self, candidate_id: str) -> list[dict[str, Any]]: ...
    def create_or_update_candidate(self, candidate: dict[str, Any]) -> dict[str, Any]: ...
    def update_candidate_stage(self, candidate_id: str, role_id: int, stage: str) -> dict[str, Any]: ...
    def add_note(self, candidate_id: str, note: str) -> dict[str, Any]: ...
    def check_duplicate(self, candidate: dict[str, Any]) -> dict[str, Any]: ...

