from __future__ import annotations

from typing import Any, Protocol


class HRISAdapter(Protocol):
    def get_open_headcount(self) -> list[dict[str, Any]]: ...
    def get_salary_band(self, role_title: str, location: str) -> dict[str, Any]: ...
    def get_hiring_manager(self, role_id: int) -> dict[str, Any]: ...
    def get_department_policy(self, department: str) -> dict[str, Any]: ...

